# Generated by Django 5.1 on 2024-09-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registercustomer_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='all_items/')),
            ],
        ),
    ]
